#!/bin/bash

IF=$1
STATUS=$2

if [[ "$IF" == eth* || "$IF" == "wlan1" ]]
then
    case "$STATUS" in
        up)
            curl -sfL https://raw.githubusercontent.com/ideascube/ansiblecube/oneUpdateFile/roles/system/files/system-upgrade.sh | bash
        ;;
        *)
            exit 0;
        ;;
    esac
fi
