# ~/.bashrc: executed by bash(1) for non-login shells.

# You may uncomment the following lines if you want `ls' to be colorized:
export LS_OPTIONS='--color=auto'
eval "`dircolors`"
alias ls='ls $LS_OPTIONS'
alias ll='ls $LS_OPTIONS -l'
alias l='ls $LS_OPTIONS -lA'

# Some more alias to avoid making mistakes:
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# ENV
export LS_OPTS='--color=auto'
export GREP_OPTIONS='--color=auto'

# Bash completion
if [ -f /etc/profile.d/bash-completion ] ; then
    source /etc/profile.d/bash-completion
elif [ -f /etc/bash_completion ] ; then
    source /etc/bash_completion
fi
