language: python
python:
  - "2.7"
sudo: false
branches:
  only:
    - master
    - oneUpdateFile
install:
- pip install -r tests/requirements-dev.txt
script:
- py.test
notifications:
    irc:
        channels:
            - "irc.freenode.net#ideascube"
        on_success: change
        on_failure: always
    email: false
