---
#
# Full playbook with exemple
#

# Switch over "localhost" or "SystemPushInstall"

# localhost is used when ansible-pull is used to play the playbook
# SystemPushInstall is used in PUSH mode and you have to set the device's IP in "hosts" file
# ex: ansible-playbook -i hosts -l SystemPushInstall -u root update_test.yml

# Please note that all system roles were played in globalInstall.yml

# Have a look at the group_vars directory and make sure all variables in those files are correct

- hosts: localhost
# - hosts: SystemPushInstall

  roles:
    # Enable or disable to suit your needs

    # This role automatically send logs to central server each time the device gets an Internet connection
    - logs

    # Install Kalite. Videos will have to be downloaded separately
    - role: kalite
      version: "0.15.0"
      lang: ["fr","en"]

    # Install ideascube in version 0.9.1, modify the release number if you need to deploy an upgrade
    - role: ideascube
      version: "0.9.1"

    # You can play a role for a specific device
    # Install App Inventor but only if the hostname match the KoomBook kb_mooc_vog_345
    - role: appinventor
      when: ansible_hostname == 'kb_mooc_vog_345'

    # Install MongoDB and BSF Campus or KoomBook EDU plate-forme on the KoomBook
    - mongodb

    - role: mook
      mook_name: bsfcampus

    - role: mook
      mook_name: koombookedu

    # Download and install ZIM file from this catalog http://catalog.ideascube.org/kiwix.yml
    # "langid" will be the name of each ZIM file to download, each name must be separated with a space
    - role: zim_install
      zim_name: "wikipedia.fr wikipedia.en"

    # Rename a device, kb-mooc-cog-492 is the old name, kb_bdi_tv5monde is the new name. Watch the - and _
    - role: rename_device
      ideascube_id: "kb_bdi_tv5monde"
      when: ansible_hostname == 'kb-mooc-cog-492'

    # Mount a network drive and import some content to ideascube.
    - role: idc_import
      content_name: "14-logiciel-libre/app.csv"

  # You can play post_tasks task, like shutdown the server only when ideascube_version.stdout is empty
  post_tasks:
    - name: Job done, let's shutdown now.
      command: shutdown -h now
      when: ideascube_version.stdout == ""
