---
- hosts: localhost
# - hosts: SystemPushInstall

  pre_tasks:
    - name: Set the LED steady before upgrading !!!
      shell: echo default-on >/sys/class/leds/a20-olinuxino-lime2:green:usr/trigger
      when: ansible_architecture == 'armv7l' and ansible_lsb.id == 'Debian'
      ignore_errors: yes
      tags: [ 'master', 'custom', 'update','idc_import','package_management','kalite_import' ]

  roles:
    - set_custom_fact
    - system
    - nginx
    - uwsgi
    - ideascube
    - kiwix
    - package_management

    - role: captive_portal
      when: ansible_local.device_list[generic_project_name].portal is defined

    - role: tinc-dynamic
      vpn_name: "testvpn"
      vpn_port: "656"
      vpn_master_server: "tincmaster"
      when: ansible_local.installed_software.management.managed_by_bsf|bool == True

    - role: tinc-dynamic
      vpn_name: "{{ ansible_local.device_list[generic_project_name].vpn.name }}"
      vpn_port: "{{ ansible_local.device_list[generic_project_name].vpn.port }}"
      vpn_master_server: "{{ ansible_local.device_list[generic_project_name].vpn.master_server }}"
      when: ansible_local.device_list[generic_project_name].vpn is defined

    - role: mook
      mook_name: bsfcampus
      mook_version: "{{ ansible_local.device_list[generic_project_name].bsfcampus.version }}"
      when: ansible_local.device_list[generic_project_name].bsfcampus is defined
        and ansible_local.device_list[generic_project_name].bsfcampus.activated|bool == True

    - role: mook
      mook_name: koombookedu
      mook_version: "{{ ansible_local.device_list[generic_project_name].koombookedu.version }}"
      when: ansible_local.device_list[generic_project_name].koombookedu is defined
        and ansible_local.device_list[generic_project_name].koombookedu.activated|bool == True

    - role: appinventor
      when: ansible_local.device_list[generic_project_name].appinventor is defined
        and ansible_local.device_list[generic_project_name].appinventor.activated|bool == True
      tags: ['custom']

    - role: kalite
      when: ansible_local.device_list[generic_project_name].kalite is defined
        and ansible_local.device_list[generic_project_name].kalite.activated|bool == True

    - role: kolibri
      when: ansible_local.device_list[generic_project_name].kolibri is defined
        and ansible_local.device_list[generic_project_name].kolibri.activated|bool == True

    - role: telegraf
      when: ansible_local.installed_software.management.managed_by_bsf|bool == True
      tags: ['custom','update']

    - role: logs
      when: ansible_local.installed_software.management.managed_by_bsf|bool == True
      tags: ['master','update']

    - role: samba
      when: ansible_local.device_list[generic_project_name].samba is defined
        and ansible_local.device_list[generic_project_name].samba|bool == True
      tags: ['custom','update']

    - role: syncthing
      when: ansible_local.device_list[generic_project_name].syncthing is defined
      tags: ['custom','update','syncthing']

    - role: modoboa
      when: ansible_local.device_list[generic_project_name].modoboa is defined
        and ansible_local.device_list[generic_project_name].modoboa.activated|bool == True
      tags: ['custom','update','modoboa']

    - role: idc_import
      when: ansible_local.device_list[generic_project_name].idc_import is defined
        and ansible_local.device_list[generic_project_name].idc_import.activated|bool == True
        and cache_machine.state|default(omit) == "present"
      tags: ['update','idc_import']

  post_tasks:
    - name: Heartbeat mode on KoomBook LED, update is over !!!
      shell: echo heartbeat >/sys/class/leds/a20-olinuxino-lime2:green:usr/trigger
      when: ansible_architecture == 'armv7l' and ansible_lsb.id == 'Debian'
      ignore_errors: yes
      tags: [ 'master', 'custom', 'update','idc_import','package_management','kalite_import' ]
