---
- hosts: localhost
# - hosts: SystemPushInstall

  pre_tasks:
    - name: Set the LED steady before upgrading !!!
      shell: echo default-on >/sys/class/leds/a20-olinuxino-lime2:green:usr/trigger
      when: ansible_architecture == 'armv7l'
      ignore_errors: yes
      tags: [ 'master', 'custom', 'update','idc_import','zim_install','kalite_import' ]

  roles:
    - set_custom_fact
    - system
    - nginx
    - uwsgi
    - ideascube
    - kiwix

    - role: captive_portal
      when: ansible_local.device_list[generic_project_name].portal is defined
        and ansible_local.device_list[generic_project_name].portal.activated|bool == True

    - role: tinc-static
      when: ansible_local.installed_software.management.managed_by_bsf|bool == True

    - role: tinc-dynamic
      when: ansible_local.installed_software.management.managed_by_bsf|bool == True

    - role: zim_install
      when: ansible_local.device_list[generic_project_name].zim_install is defined
        and ansible_local.device_list[generic_project_name].zim_install.activated|bool == True
      tags: ['custom', 'update','zim_install']

    - role: mook
      mook_name: bsfcampus
      mook_version: "{{ ansible_local.device_list[generic_project_name].bsfcampus.version }}"
      when: ansible_local.device_list[generic_project_name].bsfcampus is defined
        and ansible_local.device_list[generic_project_name].bsfcampus.activated|bool == True

    - role: mook
      mook_name: koombookedu
      mook_version: "{{ ansible_local.device_list[generic_project_name].koombookedu.version }}"
      when: ansible_local.device_list[generic_project_name].koombookedu is defined
        and ansible_local.device_list[generic_project_name].koombookedu.activated|bool == True

    - role: appinventor
      when: ansible_local.device_list[generic_project_name].appinventor is defined
        and ansible_local.device_list[generic_project_name].appinventor.activated|bool == True
      tags: ['custom']

    - role: kalite
      when: ansible_local.device_list[generic_project_name].kalite is defined
        and ansible_local.device_list[generic_project_name].kalite.activated|bool == True

    - role: logs
      when: ansible_local.installed_software.management.managed_by_bsf|bool == True
      tags: ['master','update']

    - role: idc_import
      when: ansible_local.device_list[generic_project_name].idc_import is defined
        and ansible_local.device_list[generic_project_name].idc_import.activated|bool == True
        and cache_machine.state|default(omit) == "present"
      tags: ['update','idc_import']

  post_tasks:
    - name: Heartbeat mode on KoomBook LED, update is over !!!
      shell: echo heartbeat >/sys/class/leds/a20-olinuxino-lime2:green:usr/trigger
      when: ansible_architecture == 'armv7l'
      ignore_errors: yes
      tags: [ 'master', 'custom', 'update','idc_import','zim_install','kalite_import' ]
