---
# Ansible playbook for LWB Détroit 

#It will be always localhost
- hosts: localhost

  roles:

    # Start. has to be always enable 
    - logs
    # Stop. has to be always enable 
    - tinc-static
  #   - role: ideascube
  #     version: "0.7.0-1"

  #   - kalite

  #   - role: kiwix
  #     kiwixProject: wikipedia
  #     portProject: 8002
  #     version: ['wikipedia_en_all_2015-05.zim', 'wikipedia_es_all_2015-11.zim']

  #   - role: kiwix
  #     kiwixProject: gutenberg
  #     portProject: 8007
  #     version: ['gutenberg_en_all_10_2014.zim', 'gutenberg_es_all_10_2014.zim']

  # post_tasks:
  #   - name: Job done, let's shutdown now.
  #     command: shutdown -h now
  #     when: ideascube_version.stdout == ""
