---
# Ansible playbook for KoomBook EDU RDC

#It will be always localhost
- hosts: localhost

  pre_tasks:
    - name: Upgrade U-boot
      apt: deb=http://filer.bsf-intranet.org/linux-u-boot-next-lime2_5.23_armhf.deb

  roles:
    # Has to be always enable
    - logs
    - tinc-static
    # - role: upgradeIdc
    #   version: "0.9.0"
