---
# Ansible playbook for Coeur de forêt

#It will be always localhost
- hosts: localhost

  roles:
    # Has to be always enable
    - logs
    - tinc-static
    # - role: upgradeIdc
    #   version: "0.9.3"

