- name: Change bitbucket owner repository
  replace: dest={{ mook_path }}/{{ mook_name }}/front/.git/config
    regexp='gryzzlab'
    replace='bsfcampus'
  tags:
    - update

- name: Change repository name
  replace: dest={{ mook_path }}/{{ mook_name }}/front/.git/config
    regexp='mook-bsf-front-end-backbone.git'
    replace='{{url_project_name}}.git'
  tags:
    - update

- name: Clone/update mook front
  become: True
  become_user: ideascube
  git: repo=ssh://git@altssh.bitbucket.org:443/bsfcampus/{{url_project_name}}.git 
    dest={{ mook_path }}/{{ mook_name }}/front 
    accept_hostkey=yes 
    force=yes
    version=master
    update=yes
    depth=1
  register: front_installation
  tags: ["custom","update"]
    
- name: Get and unarchive the vendor package
  become: True
  become_user: ideascube
  unarchive: src={{filer_bsf}}/vendor.zip dest={{ mook_path }}/{{ mook_name }}/front copy=no
  when: front_installation.changed == True
  tags: ["custom","update"]
      
- name: Copy config.js config files
  template: src=config.js.j2 dest={{ mook_path }}/{{ mook_name }}/front/config.js
  tags:
    - custom
    
- name: Fix rights
  file: path={{ mook_path }}/{{ mook_name }} state=directory owner={{ username }} group={{ username }} recurse=yes
  tags: ["custom","update"]