####
# Systemd startup script
####

- name: Copy template for systemd mook-sync
  template: src=mook-sync.service.j2 dest=/etc/systemd/system/mook-sync-{{ mook_name }}.service
  tags:
    - custom

- name: Enable service 
  service: name=mook-sync-{{ mook_name }}.service enabled=yes
  tags:
    - custom
    
- name: Delete old way of synching 
  lineinfile: dest=/etc/rc.local state=absent regexp='su ideascube -c'
  tags:
    - update

####
# NGINX CONFIGURATION
####

- name: Copy vhost
  template: src=vhost.j2 dest=/etc/nginx/sites-available/{{ mook_name }}
  tags:
    - custom
    
- name: Copy api vhost
  template: src=vhost-api.j2 dest=/etc/nginx/sites-available/{{ mook_name }}-api
  tags:
    - custom
    
- name: bsf campus enable Virtual host
  file: src=/etc/nginx/sites-available/{{ mook_name }} dest=/etc/nginx/sites-enabled/{{ mook_name }} state=link
  tags:
    - custom
    
- name: bsf campus api enable Virtual host
  file: src=/etc/nginx/sites-available/{{ mook_name }}-api dest=/etc/nginx/sites-enabled/{{ mook_name }}-api state=link
  notify: restart nginx
  tags:
    - custom
    
####
# UWSGI CONFIGURATION
####

- name: Copy uwsgi config files
  template: src=uwsgi-api.ini.j2 dest={{ mook_path }}/{{ mook_name }}/api/uwsgi-api.ini
  tags:
    - custom
    
- name: Symbolic link for wsgi ini file
  file: src={{ mook_path }}/{{ mook_name }}/api/uwsgi-api.ini dest=/etc/uwsgi/apps-enabled/uwsgi-{{ mook_name }}-api.ini state=link
  notify: restart uwsgi
  tags:
    - custom