---
- name: Reload systemd
  shell: systemctl daemon-reload
  tags: ['custom', 'update']

- name: restart nginx
  service: name=nginx state=restarted
  tags: ['custom', 'update']

- name: restart kolibri
  service: name=kolibri state=restarted
  tags: ['custom', 'update']
