---

- name: Add non free repository
  replace: dest=/etc/apt/sources.list
    regexp='jessie main' 
    replace='jessie main non-free'
  tags:
  - master

- name: Install the Realtek firmware for wifi interfaces
  apt: name=firmware-realtek state=present update_cache=yes
