#!/bin/bash

function die() {
        echo "$1"
        exit 1
}

if [[ -b /dev/sda && ! -b /dev/sda1 ]]; then

    # TO ENABLE ONLY ON PURPOSE : Format SSD, in case of any issue, report it !
    parted /dev/sda mklabel msdos mkpart primary ext4 0% 100% -s || die "Paritioning issue"
    mkfs.ext4 /dev/sda1 || die "/dev/sda1 can not be formated"

    # mount partition
    mount /dev/sda1 /media/hdd/ || die "Unable to mount partition"

    echo "/dev/sda1 /media/hdd/ ext4 noatime,nofail 0 0" >> /etc/fstab

    # Move ideascube files to the external HDD
    mv /home/ideascube/hdd/* /media/hdd/

    # Set permissions for ideascube user
    chown -R ideascube:ideascube /media/hdd/

    # Disable script 
    chmod -x $0

    # Rename KoomBook
    /var/lib/ansible/local/buildMyCube.sh -n kb_tgo_aneho -a rename

    reboot
fi
