#! /bin/sh

# Author: Jamie Alexandre, 2012
#
# /etc/init.d/kalite

### BEGIN INIT INFO
# Provides:          kalite
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: ka-lite daemon, a local Khan Academy content server
### END INIT INFO

set -e
. /lib/lsb/init-functions
case "$1" in
    start)
        # run ka-lite as another user, the one who generated this file
        su {{ username }} -c "kalite start"
        ;;
    stop)
        "kalite stop"
        ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  status)
    "kalite status"
    ;;
  *)
    log_success_msg "Usage: /etc/init.d/kalite {start|stop|restart|status}"
    exit 1
esac
