---
- name: Change LED state for upgrading 
  shell: echo default-on >/sys/class/leds/green\:ph20\:led2/trigger
  when: ansible_architecture == 'armhf' or ansible_architecture == 'armv7l'
  ignore_errors: yes

- name: Install last custom Kernel, Headers, DTB and U-Boot
  get_url: url=http://filer.bsf-intranet.org/{{ item }} dest=/tmp/{{ item }}
  with_items:
   - linux-dtb-next-sunxi_5.23_armhf.deb
   - linux-headers-next-sunxi_5.23_armhf.deb
   - linux-image-next-sunxi_5.23_armhf.deb
   - linux-u-boot-next-lime2_5.23_armhf.deb
  when: ansible_architecture == 'armhf' or ansible_architecture == 'armv7l'
    and ansible_version.full | version_compare('2.0', '<')

- name: Install last custom Kernel, Headers, DTB and U-Boot
  command: dpkg -i /tmp/{{ item }}
  with_items:
   - linux-dtb-next-sunxi_5.23_armhf.deb
   - linux-headers-next-sunxi_5.23_armhf.deb
   - linux-image-next-sunxi_5.23_armhf.deb
   - linux-u-boot-next-lime2_5.23_armhf.deb
  when: ansible_architecture == 'armhf' or ansible_architecture == 'armv7l'
    and ansible_version.full | version_compare('2.0', '<')
    
- name: Copy upgrade_ansible.sh
  copy: src=upgrade_ansible.sh dest=/tmp/upgrade_ansible.sh mode="u=rwx,g=r,o=r"
  when : ansible_version.full | version_compare('2.0', '<')

- name: Execute upgrade_ansible.sh
  command: /tmp/upgrade_ansible.sh
  when : ansible_version.full | version_compare('2.0', '<')  

- name: ensure custom facts directory exists
  file: >
    path=/etc/ansible/facts.d
    recurse=yes
    state=directory

- name: Create an INI file
  file: path=/etc/ansible/facts.d/installed_software.fact state=touch 

- name: Get ideascube version
  shell: dpkg-query -W  ideascube  | awk '{print $2}' ; echo
  register: ideascube_version

- name: Save Ideascube version number
  ini_file: dest=/etc/ansible/facts.d/installed_software.fact
            section=software
            option=ideascube
            value={{ ideascube_version.stdout }}

- name: Get kalite version
  shell: kalite --version ; echo
  register: kalite_version

- name: Save kalite version number
  ini_file: dest=/etc/ansible/facts.d/installed_software.fact
            section=software
            option=kalite
            value={{ kalite_version.stdout }}

- name: Register if the device is managed by BSF or not
  ini_file: dest=/etc/ansible/facts.d/installed_software.fact
    section=management
    option=managed_by_bsf
    value={{ sync_log }}

- name: Create entry to clone/pull git repository
  get_url: url=https://raw.githubusercontent.com/ideascube/ansiblecube/master/roles/network-manager/files/nm-dispatcher
    dest=/etc/NetworkManager/dispatcher.d/ansiblePullUpdate force=yes

- name: remove old way of lunching ansible-pull
  file: path=/etc/dhcp/dhclient-exit-hooks.d/ansiblePullUpdate state=absent

- name: Disable service uwsgi before upgrading ideascube 
  command: systemctl disable uwsgi

- name: Reboot device to switch to new branch
  command: shutdown -r now